### PR TITLE
Added Podman support

### PR DESCRIPTION
**Pull request by koelslaw**
added podman support to ECP to run on RHEL, ROCKY systems that have podman installed by default

### CODE REVIEW

**Comment by peasead** [comment]
Resolves #26

**Comment by peasead** [comment]
@koelslaw can you update the `README.md` to include instructions on how to install Podman?

I don't see it in my Rocky builds. I can't check right now, but I feel like its as simple as `dnf install podman` or `apt install podman`? If so, that'd be easier for Linux installations all around.

Can you check that and LMK what you recommend?

**Comment by peasead** [comment]
I just gave this a shot and had it doesn't appear that `podman` is a direct substitution for `docker`, at least how we're implementing it. Do you have something special set on your side?

<details>
  <summary>Error output</summary>

```
./elastic-container.sh start
./elastic-container.sh: line 190: docker: command not found
Passphrase has been reset. Proceeding.
Starting Elastic Stack network and containers
podman-compose version: 1.0.6
['podman', '--version', '']
using podman version: 4.2.0
** excluding:  set()
['podman', 'ps', '--filter', 'label=io.podman.compose.project=elastic-container', '-a', '--format', '{{ index .Labels "io.podman.compose.config-hash"}}']
podman volume inspect elastic-container_certs || podman volume create elastic-container_certs
['podman', 'volume', 'inspect', 'elastic-container_certs']
Error: inspecting object: no such volume elastic-container_certs
['podman', 'volume', 'create', '--label', 'io.podman.compose.project=elastic-container', '--label', 'com.docker.compose.project=elastic-container', '--driver', 'local', 'elastic-container_certs']
['podman', 'volume', 'inspect', 'elastic-container_certs']
['podman', 'network', 'exists', 'elastic-container_default']
['podman', 'network', 'create', '--label', 'io.podman.compose.project=elastic-container', '--label', 'com.docker.compose.project=elastic-container', 'elastic-container_default']
['podman', 'network', 'exists', 'elastic-container_default']
podman run --name=ecp-elasticsearch-security-setup -d --label io.podman.compose.config-hash=8127455b3dff3403bbb1c758176749ce9d4e7b183dc13c21fb3f8c55736c4315 --label io.podman.compose.project=elastic-container --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@elastic-container.service --label com.docker.compose.project=elastic-container --label com.docker.compose.project.working_dir=/home/variable/elastic-container --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=setup -v elastic-container_certs:/usr/share/elasticsearch/config/certs:z --net elastic-container_default --network-alias setup -u 0 --healthcheck-command /bin/sh -c '[ -f config/certs/elasticsearch/elasticsearch.crt ]' --healthcheck-interval 1s --healthcheck-timeout 5s --healthcheck-retries 120 docker.elastic.co/elasticsearch/elasticsearch:8.7.0 bash -c
  if [ xpassword == x ]; then
    echo "Set the ELASTIC_PASSWORD environment variable in the .env file";
    exit 1;
  elif [ xpassword == x ]; then
    echo "Set the KIBANA_PASSWORD environment variable in the .env file";
    exit 1;
  fi;
  if [ ! -f certs/ca.zip ]; then
    echo "Creating CA";
    bin/elasticsearch-certutil ca --silent --pem -out config/certs/ca.zip;
    unzip config/certs/ca.zip -d config/certs;
  fi;
  if [ ! -f certs/certs.zip ]; then
    echo "Creating certs";
    echo -ne \
    "instances:\n"\
    "  - name: elasticsearch\n"\
    "    dns:\n"\
    "      - ecp-elasticsearch\n"\
    "      - localhost\n"\
    "    ip:\n"\
    "      - 127.0.0.1\n"\
    "  - name: kibana\n"\
    "    dns:\n"\
    "      - ecp-kibana\n"\
    "      - localhost\n"\
    "    ip:\n"\
    "      - 127.0.0.1\n"\
    "  - name: fleet-server\n"\
    "    dns:\n"\
    "      - ecp-fleet-server\n"\
    "      - localhost\n"\
    "    ip:\n"\
    "      - 127.0.0.1\n"\
    > config/certs/instances.yml;
    bin/elasticsearch-certutil cert --silent --pem -out config/certs/certs.zip --in config/certs/instances.yml --ca-cert config/certs/ca/ca.crt --ca-key config/certs/ca/ca.key;
    unzip config/certs/certs.zip -d config/certs;
    cat config/certs/elasticsearch/elasticsearch.crt config/certs/ca/ca.crt > config/certs/elasticsearch/elasticsearch.chain.pem
  fi;
  echo "Setting file permissions"
  chown -R root:root config/certs;
  find . -type d -exec chmod 750 \{\} \;;
  find . -type f -exec chmod 640 \{\} \;;
  echo "Waiting for Elasticsearch availability";
  until curl -s --cacert config/certs/ca/ca.crt https://ecp-elasticsearch:9200 | grep -q "missing authentication credentials"; do sleep 30; done;
  echo "Setting kibana_system password";
  until curl -s -X POST --cacert config/certs/ca/ca.crt -u elastic:password -H "Content-Type: application/json" https://ecp-elasticsearch:9200/_security/user/kibana_system/_password -d "{\"password\":\"password\"}" | grep -q "^{}"; do sleep 10; done;
  echo "All done!";

1a3db326181d42707d1549fc8382975455f6913851984e8c417daea4320cdef9
exit code: 0
podman volume inspect elastic-container_certs || podman volume create elastic-container_certs
['podman', 'volume', 'inspect', 'elastic-container_certs']
podman volume inspect elastic-container_esdata01 || podman volume create elastic-container_esdata01
['podman', 'volume', 'inspect', 'elastic-container_esdata01']
Error: inspecting object: no such volume elastic-container_esdata01
['podman', 'volume', 'create', '--label', 'io.podman.compose.project=elastic-container', '--label', 'com.docker.compose.project=elastic-container', '--driver', 'local', 'elastic-container_esdata01']
['podman', 'volume', 'inspect', 'elastic-container_esdata01']
['podman', 'network', 'exists', 'elastic-container_default']
podman run --name=ecp-elasticsearch -d --requires=ecp-elasticsearch-security-setup --label io.podman.compose.config-hash=8127455b3dff3403bbb1c758176749ce9d4e7b183dc13c21fb3f8c55736c4315 --label io.podman.compose.project=elastic-container --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@elastic-container.service --label com.docker.compose.project=elastic-container --label com.docker.compose.project.working_dir=/home/variable/elastic-container --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=elasticsearch -e node.name=ecp-elasticsearch -e cluster.name=elastic-container -e ELASTIC_PASSWORD=password -e bootstrap.memory_lock=true -e discovery.type=single-node -e xpack.security.enabled=true -e xpack.security.http.ssl.enabled=true -e xpack.security.http.ssl.key=certs/elasticsearch/elasticsearch.key -e xpack.security.http.ssl.certificate=certs/elasticsearch/elasticsearch.chain.pem -e xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt -e xpack.security.http.ssl.verification_mode=certificate -e xpack.security.http.ssl.client_authentication=optional -e xpack.security.transport.ssl.enabled=true -e xpack.security.transport.ssl.key=certs/elasticsearch/elasticsearch.key -e xpack.security.transport.ssl.certificate=certs/elasticsearch/elasticsearch.crt -e xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt -e xpack.security.transport.ssl.verification_mode=certificate -e xpack.security.transport.ssl.client_authentication=optional -e xpack.license.self_generated.type=basic -v elastic-container_certs:/usr/share/elasticsearch/config/certs -v elastic-container_esdata01:/usr/share/elasticsearch/data --net elastic-container_default --network-alias elasticsearch -p 9200:9200 --ulimit memlock=-1:-1 -m 1073741824 --healthcheck-command /bin/sh -c 'curl -s --cacert config/certs/ca/ca.crt https://localhost:9200 | grep -q '"'"'missing authentication credentials'"'"'' --healthcheck-interval 10s --healthcheck-timeout 10s --healthcheck-retries 120 docker.elastic.co/elasticsearch/elasticsearch:8.7.0
Error: OCI runtime error: runc: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: cannot set memory limit: container could not join or create cgroup
exit code: 126
podman start ecp-elasticsearch
Error: OCI runtime error: unable to start container "5092fa80ba62b4e3b9ebc3487b8987de002ae0cf54c3ed41f6de66fdd114aade": runc: runc create failed: unable to start container process: error during container init: error setting cgroup config for procHooks process: cannot set memory limit: container could not join or create cgroup
exit code: 125
podman volume inspect elastic-container_certs || podman volume create elastic-container_certs
['podman', 'volume', 'inspect', 'elastic-container_certs']
podman volume inspect elastic-container_kibanadata || podman volume create elastic-container_kibanadata
['podman', 'volume', 'inspect', 'elastic-container_kibanadata']
Error: inspecting object: no such volume elastic-container_kibanadata
['podman', 'volume', 'create', '--label', 'io.podman.compose.project=elastic-container', '--label', 'com.docker.compose.project=elastic-container', '--driver', 'local', 'elastic-container_kibanadata']
['podman', 'volume', 'inspect', 'elastic-container_kibanadata']
['podman', 'network', 'exists', 'elastic-container_default']
podman run --name=ecp-kibana -d --requires=ecp-elasticsearch,ecp-elasticsearch-security-setup --label io.podman.compose.config-hash=8127455b3dff3403bbb1c758176749ce9d4e7b183dc13c21fb3f8c55736c4315 --label io.podman.compose.project=elastic-container --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@elastic-container.service --label com.docker.compose.project=elastic-container --label com.docker.compose.project.working_dir=/home/variable/elastic-container --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=kibana -e SERVER_NAME=ecp-kibana -e ELASTICSEARCH_HOSTS=https://ecp-elasticsearch:9200 -e ELASTICSEARCH_USERNAME=kibana_system -e ELASTICSEARCH_PASSWORD=password -e ELASTICSEARCH_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt -e SERVER_SSL_ENABLED=true -e SERVER_SSL_CERTIFICATE=config/certs/kibana/kibana.crt -e SERVER_SSL_KEY=config/certs/kibana/kibana.key -e SERVER_SSL_CERTIFICATEAUTHORITIES=config/certs/ca/ca.crt -v elastic-container_certs:/usr/share/kibana/config/certs:z -v elastic-container_kibanadata:/usr/share/kibana/data -v /home/variable/elastic-container/kibana.yml:/usr/share/kibana/config/kibana.yml:Z --net elastic-container_default --network-alias kibana -p 5601:5601 -m 1073741824 --healthcheck-command /bin/sh -c 'curl -I -s --cacert config/certs/ca/ca.crt https://localhost:5601 | grep -q '"'"'HTTP/1.1 302 Found'"'"'' --healthcheck-interval 10s --healthcheck-timeout 10s --healthcheck-retries 120 docker.elastic.co/kibana/kibana:8.7.0
Error: error generating dependency graph for container c910f8093f35a4cc5a706b00cc8a35d047e5a631cb58f9bf9c511ab8b052a5df: container 5092fa80ba62b4e3b9ebc3487b8987de002ae0cf54c3ed41f6de66fdd114aade depends on container 1a3db326181d42707d1549fc8382975455f6913851984e8c417daea4320cdef9 not found in input list: no such container
exit code: 127
podman start ecp-kibana
Error: unable to start container "c910f8093f35a4cc5a706b00cc8a35d047e5a631cb58f9bf9c511ab8b052a5df": error generating dependency graph for container c910f8093f35a4cc5a706b00cc8a35d047e5a631cb58f9bf9c511ab8b052a5df: container 5092fa80ba62b4e3b9ebc3487b8987de002ae0cf54c3ed41f6de66fdd114aade depends on container 1a3db326181d42707d1549fc8382975455f6913851984e8c417daea4320cdef9 not found in input list: no such container
exit code: 125
podman volume inspect elastic-container_certs || podman volume create elastic-container_certs
['podman', 'volume', 'inspect', 'elastic-container_certs']
['podman', 'network', 'exists', 'elastic-container_default']
podman run --name=ecp-fleet-server -d --requires=ecp-kibana,ecp-elasticsearch,ecp-elasticsearch-security-setup --label io.podman.compose.config-hash=8127455b3dff3403bbb1c758176749ce9d4e7b183dc13c21fb3f8c55736c4315 --label io.podman.compose.project=elastic-container --label io.podman.compose.version=1.0.6 --label PODMAN_SYSTEMD_UNIT=podman-compose@elastic-container.service --label com.docker.compose.project=elastic-container --label com.docker.compose.project.working_dir=/home/variable/elastic-container --label com.docker.compose.project.config_files=docker-compose.yml --label com.docker.compose.container-number=1 --label com.docker.compose.service=fleet-server -e FLEET_ENROLL=1 -e FLEET_SERVER_POLICY_ID=fleet-server-policy -e FLEET_SERVER_ENABLE=1 -e KIBANA_FLEET_SETUP=1 -e KIBANA_HOST=https://ecp-kibana:5601 -e FLEET_URL=https://ecp-fleet-server:8220 -e FLEET_SERVER_ELASTICSEARCH_HOST=https://ecp-elasticsearch:9200 -e FLEET_CA=/certs/ca/ca.crt -e KIBANA_FLEET_USERNAME=elastic -e KIBANA_FLEET_PASSWORD=password -e FLEET_SERVER_CERT=/certs/fleet-server/fleet-server.crt -e FLEET_SERVER_CERT_KEY=/certs/fleet-server/fleet-server.key -e FLEET_SERVER_ELASTICSEARCH_CA=/certs/ca/ca.crt -e KIBANA_FLEET_CA=/certs/ca/ca.crt -v elastic-container_certs:/certs:z --net elastic-container_default --network-alias fleet-server -p 8220:8220 -u root --restart always docker.elastic.co/beats/elastic-agent:8.7.0
Error: error generating dependency graph for container 40c1c2967b85d3cb70927339353974937eeb42db59bc04da576f161d6444828d: container c910f8093f35a4cc5a706b00cc8a35d047e5a631cb58f9bf9c511ab8b052a5df depends on container 1a3db326181d42707d1549fc8382975455f6913851984e8c417daea4320cdef9 not found in input list: no such container
exit code: 127
podman start ecp-fleet-server
Error: unable to start container "40c1c2967b85d3cb70927339353974937eeb42db59bc04da576f161d6444828d": error generating dependency graph for container 40c1c2967b85d3cb70927339353974937eeb42db59bc04da576f161d6444828d: container 5092fa80ba62b4e3b9ebc3487b8987de002ae0cf54c3ed41f6de66fdd114aade depends on container 1a3db326181d42707d1549fc8382975455f6913851984e8c417daea4320cdef9 not found in input list: no such container
exit code: 125
```
</details>

**Comment by koelslaw** [comment]
It unfortunately needs the all powerful `sudo`. The `--priveldged` flag may allow the required "permissions" but i haven't tested it to know. If you feel like its a better option I can explore that. 

I can certainly update the README.md

**Comment by koelslaw** [comment]
@peasead I have made the requested changes to the docs. Tested on Fedora 37 and Rocky 9.

**Review by DefSecSentinel — APPROVED** [review]
LGTM

**Comment by peasead** [comment]
Thanks for your patience. I'll make a fresh check tonight

**Comment by koelslaw** [comment]
@peasead take your time. just glad to contribute.

**Comment by koelslaw** [comment]
Podman/podman-compose is completely ignoring health checks at the moment and tries to stand up fleet server immediately. This wouldn't necessarily be an issue but It also ignore the `restart` flag after a certain amount of time or attempts (not sure which). Fleet containers stops restarting and your left without it. If you run shell or start the container individually it takes right off. :shrug:  More work to try and figure this out.

**Pull request closed without merging**
